fix java package declarations?
Test device saw app crash on start. Saw this:

```
java.lang.RuntimeException: Unable to instantiate receiver riccio.co2.client.BootUpReceiver: java.lang.ClassNotFoundException: Didn't find class "riccio.co2.client.BootUpReceiver" on path: DexPathList[...long args...]
[...stack...]
Caused by: java.lang.ClassNotFoundException: Didn't find class "riccio.co2.client.BootUpReceiver" on path: DexPathList[...long args...]

```
Pulled ADB from device with `adb shell pm path riccio.co2.client` then `adb pull /data/app/riccio.co2.client-jkvAH03NbD_1SJ6DooSBBg==/base.apk` to a `inspect_co2_tracker_apk` dir in documents, opened it in Android Studio, which showed `BootUpHandlerService` and `BootUpReceiver

Problem likely an issue with package declarations in java files (fucking java):
https://stackoverflow.com/questions/36154340/android-missing-package-statement-activity-class-does-not-exist